name: Sample build

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Build
      run: |
        ./gradlew assembleDebug
    - name: Store generated APK file
      uses: actions/upload-artifact@v4
      with:
        name: sample-debug
        path: ./sample/build/outputs/apk/debug/sample-debug.apk
